baseurl: /
title: TipsyData
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: Kelvin M. Muia is a Tipsy-data Analyst based in Nairobi, Kenya.
  name: Kelvin Mwaka Muia
Params:
  authorbox: yes
  description: Kelvin Mwaka Muia's personal blog about everything tipsy data analytics.
  logo:
    subtitle: How tipsy do you like your data?
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
