baseurl: "https://tipsydata.netlify.app/"
title: TipsyData
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: "tipsydata" 
googleAnalytics: "G-YNMLVTTZ1X"
Content-Type: text/plain
Author:
  avatar: img/avatar.png
  bio: Kelvin M. Muia is a Tipsy-data Analyst based in Nairobi, Kenya.
  name: Kelvin Mwaka Muia
Params:
  authorbox: yes
  description: Kelvin Mwaka Muia's personal blog about everything tipsy data analytics.
  logo:
    subtitle: Data Science demystified with R.
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: yes
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: yes
  social:
  - name: LinkedIn
    icon: linkedin
    link: https://www.linkedin.com/kelvin-mwaka-muia
  - name: Twitter
    icon: twitter
    link: https://twitter.com/mwakakelvin
  - name: Facebook
    icon: facebook
    link: https://web.facebook.com/tipsydata
  - name: GitHub
    icon: github
    link: https://github.com/kelvinmmuia
